### ISSUE TITLE
msync fails with nilClass error

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync#172]
Note: This affects the master branch, not the latest release:

during the latest modulesync I got this error:
```
NoMethodError: undefined method `[]' for nil:NilClass
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bundler/gems/modulesync-fe30d219fff4/lib/modulesync.rb:167:in `manage_pr'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bundler/gems/modulesync-fe30d219fff4/lib/modulesync.rb:136:in `manage_module'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bundler/gems/modulesync-fe30d219fff4/lib/modulesync.rb:187:in `block in update'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bundler/gems/modulesync-fe30d219fff4/lib/modulesync.rb:185:in `each'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bundler/gems/modulesync-fe30d219fff4/lib/modulesync.rb:185:in `update'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bundler/gems/modulesync-fe30d219fff4/lib/modulesync/cli.rb:136:in `update'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bundler/gems/modulesync-fe30d219fff4/bin/msync:8:in `<top (required)>'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bin/msync:23:in `load'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.6.0/bin/msync:23:in `<top (required)>'
```

for a module that already had a pull request opened. also msync doesn't display the PR url anymore :(

**Comment by bastelfreak** [comment]
And with latest 1.3.0 release:

```
bastelfreak@bastelfreak-ws ~/modulesync_config $ bundle exec msync update --filter collectd --message "modulesync 3.0.0" --pr --pr-title "modulesync 3.0.0" --pr-labels modulesync
/home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: warning: `_1' is reserved for numbered parameter; consider another name
/home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: warning: `_2' is reserved for numbered parameter; consider another name
/home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/mime-types-2.99.3/lib/mime/types/logger.rb:26: warning: `_3' is reserved for numbered parameter; consider another name
Syncing voxpupuli/puppet-collectd
Overriding any local changes to repositories in modules
Creating new branch modulesync
Error while updating puppet-collectd
bundler: failed to load command: msync (/home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/bin/msync)
NoMethodError: undefined method `[]' for nil:NilClass
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/modulesync-1.3.0/lib/modulesync.rb:186:in `pr'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/modulesync-1.3.0/lib/modulesync.rb:137:in `manage_module'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/modulesync-1.3.0/lib/modulesync.rb:174:in `block in update'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/modulesync-1.3.0/lib/modulesync.rb:172:in `each'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/modulesync-1.3.0/lib/modulesync.rb:172:in `update'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/modulesync-1.3.0/lib/modulesync/cli.rb:142:in `update'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/gems/modulesync-1.3.0/bin/msync:8:in `<top (required)>'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/bin/msync:23:in `load'
  /home/bastelfreak/modulesync_config/.vendor/ruby/2.7.0/bin/msync:23:in `<top (required)>'
bastelfreak@bastelfreak-ws ~/modulesync_config $
```

@ekohl @raphink any ideas?

**Comment by raphink** [comment]
Looks like it's failing on line 186 because `module_options` is `nil`.

**Comment by bastelfreak** [comment]
the workaround is:

converting this:

```yaml
---
- puppet-allknowingdns
```

to this:

```yaml
---
puppet-allknowingdns: {}
```

I couldn't find any option that we need. all our modules are in the same namespace. It would probably be good if lists still work.
