### ISSUE TITLE
msync update --noop is broken with git 1.17.x

### ISSUE THREAD

**Issue by kajinamit** [voxpupuli/modulesync#259]
We recently noticed the msync command fails with the following traceback.
Further investigation turns out git library has been bumped from git 1.14.0 to 1.17.2 (we found the error with 1.17.1 as well) and that is the trigger.
If we pin it to 1.14.0 then we no longer observe the failure.

```
$ /home/zuul/workspace/.bundled_gems/bin/bundle exec msync update --noop
Syncing 'puppet-whazz'
/home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/repository.rb:37:in `default_branch': undefined method `[]' for nil:NilClass (NoMethodError)
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/repository.rb:55:in `switch'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/repository.rb:86:in `prepare_workspace'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:122:in `manage_module'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:178:in `block in update'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:177:in `each'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync.rb:177:in `update'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/cli.rb:149:in `update'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
    from /home/zuul/workspace/.bundled_gems/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/lib/modulesync/cli/thor.rb:21:in `start'
    from /home/zuul/workspace/.bundled_gems/gems/modulesync-2.5.0/bin/msync:24:in `<top (required)>'
    from /home/zuul/workspace/.bundled_gems/bin/msync:25:in `load'
    from /home/zuul/workspace/.bundled_gems/bin/msync:25:in `<main>'
ERROR
```

The list of modules installed.
```
 Installing addressable 2.8.1
 Installing domain_name 0.5.20190701
 Installing faraday 2.7.4
 Installing faraday-net_http 3.0.2
 Installing git 1.17.2
 Installing gitlab 4.19.0
 Installing http-accept 1.7.0
 Installing httparty 0.21.0
 Installing http-cookie 1.0.5
 Installing json_pure 2.6.3
 Installing mime-types 3.4.1
 Installing mime-types-data 3.2023.0218.1
 Installing mini_mime 1.1.2
 Installing minitar 0.9
 Installing modulesync 2.5.0
 Installing multi_xml 0.6.0
 Installing netrc 0.11.0
 Installing octokit 4.25.1
 Installing pathspec 1.1.3
 Installing public_suffix 5.0.1
 Installing puppet-blacksmith 6.1.1
 Installing puppet-modulebuilder 0.3.0
 Installing rchardet 1.8.0
 Installing rest-client 2.1.0
 Installing ruby2_keywords 0.0.5
 Installing sawyer 0.9.2
 Installing terminal-table 3.0.2
 Installing thor 1.2.1
 Installing unf 0.1.4
 Installing unf_ext 0.0.8.2 with native extensions
 Installing unicode-display_width 2.4.2
```

Operating System: Ubuntu Jammy (22.04)
Ruby version: 3.0

**Comment by bastelfreak** [comment]
@alexjfisher didn't you notice some issues with pdksync and the git gem as well?

**Comment by alexjfisher** [comment]
Yes, but my issue was fixed in `1.17.2`...

**Comment by alexjfisher** [comment]
a `git bisect` finds this commit as where the behaviour changes. https://github.com/ruby-git/ruby-git/commit/5c6833f487f2ca43240c0e11ac3621ec2559b031

**Comment by alexjfisher** [comment]
yeah, I was looking at that.

**Comment by alexjfisher** [comment]
I'll submit a PR.

**Comment by saz** [comment]
FYI: the last version of `git` working for me completely is `1.13.2`

`1.14.0` includes https://github.com/ruby-git/ruby-git/pull/622 which breaks some git commands (e.g. `repo.commit`).
